arch:
    max_epochs: 200

checkpoint:
    # Folder where .ckpt files will be saved during training
    filepath: /workspace/packnet-sfm/results/chept
    save_top_k: -1

model:
    # checkpoint_path: /workspace/packnet-sfm/results/chept/hearty-wood-10/epoch=04_optitrack_1-optitrack_1_part1-loss=0.000.ckpt
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        # should be multiple of 32
        # image_shape: (352, 480)
        image_shape: (384, 512)
        # image_shape: (288, 384)
        # image_shape: (32, 32)

    train:
        batch_size: 4
        dataset: ['KITTI']
        path: ['/data/datasets/tello_crop/tello_crop_exp_room',
               '/data/datasets/tello_crop/tello_crop_exp_room',
               '/data/datasets/tello_crop/tello_crop_exp_room',
               '/data/datasets/tello_crop/tello_crop_exp_room',
               '/data/datasets/tello_crop/tello_crop_exp_room',
               '/data/datasets/tello_crop/tello_crop_exp_room',
               '/data/datasets/tello_crop/tello_crop_exp_room',

               '/data/datasets/tello_crop/tello_crop_exp_roombackward',
               '/data/datasets/tello_crop/tello_crop_exp_roombackward',
               '/data/datasets/tello_crop/tello_crop_exp_roombackward',
               '/data/datasets/tello_crop/tello_crop_exp_roombackward',

               '/data/datasets/tello_crop/tello_crop_exp_roombackward_2',
               '/data/datasets/tello_crop/tello_crop_exp_roombackward_2',
               '/data/datasets/tello_crop/tello_crop_exp_roombackward_2',
               
               '/data/datasets/tello_crop/tello_crop_my_desk',
               '/data/datasets/tello_crop/tello_crop_my_desk',
               '/data/datasets/tello_crop/tello_crop_my_desk',
               '/data/datasets/tello_crop/tello_crop_my_desk',
               '/data/datasets/tello_crop/tello_crop_my_desk',

               '/data/datasets/tello_crop/tello_crop_workshop',
               '/data/datasets/tello_crop/tello_crop_workshop',
               '/data/datasets/tello_crop/tello_crop_workshop',

               '/data/datasets/tello_crop/tello_crop_workshop_rightside',
               '/data/datasets/tello_crop/tello_crop_workshop_rightside',

               '/data/datasets/tello_crop/tello_crop_bed',
               
               '/data/datasets/tello_crop/tello_crop_boat'


               ]
        split: ['tello_crop_exp_room_part1.txt',
                'tello_crop_exp_room_part2.txt',
                'tello_crop_exp_room_part3.txt',
                'tello_crop_exp_room_part5.txt',
                'tello_crop_exp_room_part6.txt',
                'tello_crop_exp_room_part7.txt',
                'tello_crop_exp_room_part8.txt',

                'tello_crop_exp_roombackward_part1.txt',
                'tello_crop_exp_roombackward_part2.txt',
                'tello_crop_exp_roombackward_part3.txt',
                'tello_crop_exp_roombackward_part4.txt',

                'tello_crop_exp_roombackward_2_part1.txt',
                'tello_crop_exp_roombackward_2_part2.txt',
                'tello_crop_exp_roombackward_2_part3.txt',

                'tello_crop_my_desk_part1.txt',
                'tello_crop_my_desk_part2.txt',
                'tello_crop_my_desk_part3.txt',
                'tello_crop_my_desk_part4.txt',
                'tello_crop_my_desk_part5.txt',

                'tello_crop_workshop_part1.txt',
                'tello_crop_workshop_part2.txt',
                'tello_crop_workshop_part3.txt',

                'tello_crop_workshop_rightside_part1.txt',
                'tello_crop_workshop_rightside_part2.txt',

                'tello_crop_bed_part1.txt',
                'tello_crop_boat_part1.txt',

                
                ]
        repeat: [3]
    validation:
        dataset: ['KITTI']
        path: ['/data/datasets/tello_crop/tello_crop_exp_room',
               '/data/datasets/tello_crop/tello_crop_exp_room',

                
              ]
        split: ['tello_crop_exp_room_part1.txt',
                'tello_crop_exp_room_part4.txt',
                ]

wandb:
    dry_run: False
