arch:
    max_epochs: 60

checkpoint:
    # Folder where .ckpt files will be saved during training
    filepath: /workspace/packnet-sfm/results/chept
    save_top_k: -1

model:
    name: 'SelfSupModel'
    # checkpoint_path: /workspace/packnet-sfm/trained_models/PackNet01_MR_velsup_CStoK.ckpt
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.000025
        pose:
            lr: 0.000025
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        # should be multiple of 32
        image_shape: (352, 480)
        # image_shape: (32, 32)
    train:
        batch_size: 4
        dataset: ['KITTI']
        path: ['/data/datasets/rolling_shutter_rect_2']
        split: ['train.txt']
        # split: ['seq01_split.txt', 
        #         'seq02_split.txt', 
        #         'seq03_split.txt', 
        #         'seq05_split.txt',
        #         'seq06_split.txt',
        #         'seq07_split.txt',
        #         'seq08_split.txt',
        #         'seq09_split.txt',
        #         'seq10_split.txt']
        repeat: [2]
    validation:
        dataset: ['KITTI']
        path: ['/data/datasets/rolling_shutter_rect_2']
        split: ['eval.txt']
    # test:
    #     dataset: ['KITTI']
    #     path: ['/data/datasets/rolling_shutter_rect']
    #     split: ['seq04_split.txt']

wandb:
    dry_run: False
