wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
arch:
  desc: null
  value:
    max_epochs: 30
    min_epochs: 1
    seed: 42
checkpoint:
  desc: null
  value:
    filepath: /workspace/packnet-sfm/results/chept/amber-donkey-1/{epoch:02d}_{rs_vio_rect-split_seq4-loss:.3f}
    mode: auto
    monitor: rs_vio_rect-split_seq4-loss
    monitor_index: 0
    s3_frequency: 1
    s3_path: ''
    s3_url: https://s3.console.aws.amazon.com/s3/buckets//amber-donkey-1
    save_top_k: -1
config:
  desc: null
  value: configs/tum_rs_vio.yaml
datasets:
  desc: null
  value:
    augmentation:
      image_shape:
      - 32
      - 32
      jittering:
      - 0.2
      - 0.2
      - 0.2
      - 0.05
    test:
      back_context: 0
      batch_size: 1
      cameras:
      - []
      dataset:
      - KITTI
      depth_type:
      - ''
      forward_context: 0
      num_logs: 5
      num_workers: 8
      path:
      - /data/datasets/rs_vio_rect
      split:
      - split_seq4.txt
    train:
      back_context: 1
      batch_size: 4
      cameras:
      - []
      dataset:
      - KITTI
      depth_type:
      - ''
      forward_context: 1
      num_logs: 5
      num_workers: 16
      path:
      - /data/datasets/rs_vio_rect
      repeat:
      - 1
      split:
      - split_seq4.txt
    validation:
      back_context: 0
      batch_size: 1
      cameras:
      - []
      dataset:
      - KITTI
      depth_type:
      - ''
      forward_context: 0
      num_logs: 5
      num_workers: 8
      path:
      - /data/datasets/rs_vio_rect
      split:
      - split_seq4.txt
debug:
  desc: null
  value: false
default:
  desc: null
  value: configs/default_config
model:
  desc: null
  value:
    checkpoint_path: ''
    depth_net:
      checkpoint_path: ''
      dropout: 0.0
      name: PackNet01
      version: 1A
    loss:
      C1: 0.0001
      C2: 0.0009
      automask_loss: true
      clip_loss: 0.0
      disp_norm: true
      flip_lr_prob: 0.5
      num_scales: 4
      occ_reg_weight: 0.1
      padding_mode: zeros
      photometric_reduce_op: min
      progressive_scaling: 0.0
      rotation_mode: euler
      smooth_loss_weight: 0.001
      ssim_loss_weight: 0.85
      supervised_loss_weight: 0.9
      supervised_method: sparse-l1
      supervised_num_scales: 4
      upsample_depth_maps: true
      velocity_loss_weight: 0.1
    name: SelfSupModel
    optimizer:
      depth:
        lr: 2.5e-05
        weight_decay: 0.0
      name: Adam
      pose:
        lr: 2.5e-05
        weight_decay: 0.0
    params:
      crop: garg
      max_depth: 80.0
      min_depth: 0.0
    pose_net:
      checkpoint_path: ''
      dropout: 0.0
      name: PoseNet
      version: ''
    scheduler:
      T_max: 20
      gamma: 0.5
      name: StepLR
      step_size: 30
name:
  desc: null
  value: amber-donkey-1
prepared:
  desc: null
  value: true
save:
  desc: null
  value:
    depth:
      npz: true
      png: true
      rgb: true
      viz: true
    folder: ''
    pretrained: ''
wandb:
  desc: null
  value:
    dir: ''
    dry_run: false
    entity: surfii3z
    name: amber-donkey-1
    project: packnet_sfm_training
    tags: []
    url: https://app.wandb.ai/surfii3z/packnet_sfm_training/runs/3mx2bntz
